# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccesslog',
            name='api_version',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='apiaccesslog',
            name='user_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
