# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0007_emailcheckedbyus_emailcheckedbyushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcheckedbyus',
            name='contact_from_db2',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api_core.ContactFromdb2'),
        ),
    ]
