# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0008_auto_20170508_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcheckedbyus',
            old_name='is_rejected_instantly',
            new_name='is_rejected',
        ),
        migrations.RenameField(
            model_name='emailcheckedbyushistory',
            old_name='is_rejected_instantly',
            new_name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='emailcheckedbyus',
            name='is_rejected_later',
        ),
        migrations.RemoveField(
            model_name='emailcheckedbyushistory',
            name='is_rejected_later',
        ),
    ]
