# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0009_auto_20170516_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'sender_email',
            },
        ),
        migrations.AddField(
            model_name='emailcheckedbyus',
            name='sender_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_core.SenderEmail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcheckedbyushistory',
            name='sender_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_core.SenderEmail'),
            preserve_default=False,
        ),
    ]
