# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0010_auto_20170516_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
