# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('api_core', '0011_customer_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='api_right',
        ),
        migrations.AddField(
            model_name='customer',
            name='current_period_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='spare_requests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApiRight',
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.Customer'),
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='customer_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.CustomerAction'),
        ),
    ]
