# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0012_auto_20170704_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
            preserve_default=False,
        ),
    ]
