#-*- coding: utf-8 -*-

company_size_mapping_dict = {
	"11 - 50":"11-50",
	"51 - 100":"51-100",
	"10,000+":"10000+",
	"5,001 - 10,000":"5001-10000",
	"1,001 - 5,000":"1001-5000",
	"0 - 5":"0-5",
	"101 - 500":"101-500",
	"6 - 10":"6-10",
	"501 - 1,000":"501-1000",
	u"201-500 employés":"201-500",
	"Moi uniquement":"1",
	"501-1000 employees":"501-1000",
	u"1-10 employés":"1-10",
	"5001-10,000 employees":"5001-10000",
	"10,001+ employees":"10000+",
	"11-50 employés":"10-50",
	u"1001-5 000 employés":"1001-5000",
	u"+ de 10 000 employés":"10000+",
	"51-200 employees":"51-200",
	u"501-1 000 employés":"501-1000",
	"1001-5000 employees":"1001-5000",
	"11-50 employees":"11-50",
	u"5 001-10 000 employés":"5001-10000",
	"1-10 employees":"1-10",
	u"51-200 employés":"51-200",
	"Myself Only":"1",
	"201-500 employees":"201-500"
}

french_to_english_country_mapping_dict = {
	u"Andorre":"Andorra",
	u"Émirats arabes unis":"United Arab Emirates",
	u"Afghanistan":"Afghanistan",
	u"Antigua et Barbuda":"Antigua and Barbuda",
	u"Anguilla":"Anguilla",
	u"Albanie":"Albania",
	u"Arménie":"Armenia",
	u"Antilles néerlandaises":"Netherlands Antilles",
	u"Angola":"Angola",
	u"Antartique":"Antarctica",
	u"Argentine":"Argentina ",
	u"Samoa américaines":"American Samoa",
	u"Autriche":"Austria",
	u"Australie":"Australia",
	u"Aruba":"Aruba",
	u"Azerbaïdjan":"Azerbaijan",
	u"Bosnie-Herzégovine":"Bosnia and Herzegovina",
	u"Barbades":"Barbados",
	u"Bangladesh":"Bangladesh",
	u"Belgique":"Belgium",
	u"Burkina":"Burkina",
	u"Bulgarie":"Bulgaria",
	u"Bahreïn":"Bahrain",
	u"Burundi":"Burundi",
	u"Bénin":"Benin",
	u"Saint-Barthélemy":"Saint Barthelemy",
	u"Bermudes":"Bermuda",
	u"Brunei":"Brunei",
	u"Bolivie":"Bolivia",
	u"Brésil":"Brazil",
	u"Bahamas":"Bahamas",
	u"Bhoutan":"Bhutan",
	u"Botswana":"Botswana",
	u"Biélorussie":"Belarus",
	u"Bélize":"Belize",
	u"Canada":"Canada",
	u"Îles Cocos":"Cocos (Keeling) Islands",
	u"République démocratique du Congo":"Democratic Republic of the Congo",
	u"République centrafricaine":"Republica Central Africană",
	u"République du Congo":"Republic of the Congo",
	u"Suisse":"Switzerland",
	u"Côte d'Ivoire":"Ivory Coast",
	u"Îles Cook":"Cook Islands",
	u"Chili":"Chile",
	u"Cameroun":"Cameroon",
	u"Chine":"China",
	u"Colombie":"Colombia",
	u"Costa Rica":"Costa Rica",
	u"Cuba":"Cuba",
	u"Cap Vert":"Cape Verde",
	u"Île Christmas":"Christmas Island",
	u"Chypre":"Cyprus",
	u"République tchèque":"Czech Republic",
	u"Allemagne":"Germany",
	u"Djibouti":"Djibouti",
	u"Danemark":"Denmark",
	u"Dominique":"Dominica",
	u"République dominicaine":"Dominican Republic",
	u"Algérie":"Algeria",
	u"Équateur":"Ecuador",
	u"Estonie":"Estonia",
	u"Égypte":"Egypt",
	u"Érythrée":"Eritrea",
	u"Espagne":"Spain",
	u"Éthiopie":"Ethiopia",
	u"Finlande":"Finland",
	u"Fidji":"Fiji",
	u"Îles Malouines":"Falkland Islands",
	u"Micronésie":"Micronesia",
	u"Îles Féroé":"Islas Faroe",
	u"France":"France",
	u"Gabon":"Gabon",
	u"Royaume-Uni":"United Kingdom",
	u"Grenade":"Grenada",
	u"Géorgie":"Georgia",
	u"Guyane":"French Guiana",
	u"Ghana":"Ghana",
	u"Gibraltar":"Gibraltar",
	u"Groenland":"Greenland",
	u"Gambie":"Gambia",
	u"Guinée":"Guinea",
	u"Guadeloupe":"Guadeloupe",
	u"Guinée ":"Guinée équatoriale",
	u"Grèce":"Greece",
	u"Guatemala":"Guatemala",
	u"Guam":"Guam",
	u"Guinée-Bissau":"Guinea-Bissau",
	u"Guyane":"Guyana",
	u"Hong Kong":"Hong Kong",
	u"Honduras":"Honduras",
	u"Croatie":"Croatia",
	u"Haïti":"Haiti",
	u"Hongrie":"Hungary",
	u"Indonésie":"Indonesia",
	u"Irlande":"Ireland",
	u"Israël":"Israel",
	u"Île de Man":"Isle of Man",
	u"Inde":"India",
	u"Irak":"Iraq",
	u"Iran":"Iran",
	u"Islande":"Iceland",
	u"Italie":"Italy",
	u"Jamaïque":"Jamaica",
	u"Jordanie":"Jordan",
	u"Japon":"Japan",
	u"Kenya":"Kenya",
	u"Kirghizistan":"Kyrgyzstan",
	u"Cambodge":"Cambodia",
	u"Kiribati":"Kiribati",
	u"Comores":"Comoros",
	u"Saint-Christophe-et-Niévès":"Saint Kitts and Nevis",
	u"Corée du Nord":"North Korea",
	u"Corée du Sud":"South Korea",
	u"Koweït":"Kuwait",
	u"Îles Caïmans":"Cayman Islands",
	u"Kazakhstan":"Kazakhstan",
	u"Laos":"Laos",
	u"Liban":"Lebanon",
	u"Sainte-Lucie":"Saint Lucia",
	u"Liechtenstein":"Liechtenstein",
	u"Sri Lanka":"Sri Lanka",
	u"Liberia":"Liberia",
	u"Lesotho":"Lesotho",
	u"Lituanie":"Lithuania",
	u"Luxembourg":"Luxembourg",
	u"Lettonie":"Latvia",
	u"Libye":"Libya",
	u"Maroc":"Morocco",
	u"Monaco":"Monaco",
	u"Moldavie":"Moldova",
	u"Monténégro":"Montenegro",
	u"Madagascar":"Madagascar",
	u"Îles Marshall":"Marshall Islands",
	u"Macédoine":"Macedonia",
	u"Mali":"Mali",
	u"Birmanie":"Burma (Myanmar)",
	u"Mongolie":"Mongolia",
	u"Macao":"Macau",
	u"Îles Mariannes du Nord":"Northern Mariana",
	u"Mauritanie":"Mauritania",
	u"Abbaye de Montserrat":"Montserrat",
	u"Malte":"Malta",
	u"Maurice":"Republic of Mauritius",
	u"Maldives":"Maldives",
	u"Malawi":"Malawi",
	u"Mexique":"Mexico",
	u"Malaisie":"Malaysia",
	u"Mozambique":"Mozambique",
	u"Namibie":"Namibia",
	u"Nouvelle-Calédonie":"New Caledonia",
	u"Niger":"Niger",
	u"Nigeria":"Nigeria",
	u"Nicaragua":"Nicaragua",
	u"Pays-Bas":"Netherlands",
	u"Norvège":"Norway",
	u"Népal":"Nepal",
	u"Nauru":"Nauru",
	u"Niue":"Niue",
	u"Nouvelle-Zélande":"New Zeland",
	u"Oman":"Oman",
	u"Panama":"Panama",
	u"Pérou":"Peru",
	u"Polynésie française":"French Polynesia",
	u"Papouasie-Nouvelle-Guinée":"Papua New Guinea",
	u"Philippines":"Philippines",
	u"Pakistan":"Pakistan",
	u"Pologne":"Poland",
	u"Saint-Pierre-et-Miquelon":"Saint Pierre and Miguelon",
	u"Îles Pitcairn":"Pitcairn Islands",
	u"Porto Rico":"Puerto Rico",
	u"Portugal":"Portugal",
	u"Palaos":"Palau ",
	u"Paraguay":"Paraguay",
	u"Qatar":"Qatar ",
	u"Roumanie":"Romania",
	u"Serbie":"Serbia",
	u"Russie":"Russia",
	u"Rwanda":"Rwanda",
	u"Arabie saoudite":"Saudi Arabia",
	u"Salomon":"Solomon Islands",
	u"Seychelles":"Seychelles ",
	u"Soudan":"Sudan",
	u"Suède":"Sweden",
	u"Singapour":"Singapore",
	u"Sainte-Hélène":"Saint Helena",
	u"Slovénie":"Slovenia ",
	u"Slovaquie":"Slovakia",
	u"Sierra Leone":"Sierra Leone",
	u"Saint-Marin":"San Marino",
	u"Sénégal":"Senegal",
	u"Somalie":"Somalia",
	u"Suriname":"Suriname",
	u"Sao Tomé-et-Principe":"Sao Tomé and Principe",
	u"Salvador":"El Salvador",
	u"Syrie":"Syria",
	u"Swaziland":"Swaziland",
	u"Îles Turks-et-Caïcos":"Turks and Caicos Islands",
	u"Tchad":"Chad",
	u"Togo":"Togo",
	u"Thaïlande":"Thailand",
	u"Tadjikistan":"Tajikistan",
	u"Tokelau":"Tokelau",
	u"Timor oriental":"Timor-Leste",
	u"Turkménistan":"Turkmenistan",
	u"Tunisie":"Tunisia",
	u"Tonga":"Tonga",
	u"Turquie":"Turkey",
	u"Trinité-et-Tobago":"Trinidad and Tobago",
	u"Tuvalu":"Tuvalu",
	u"Taïwan":"Taiwan",
	u"Tanzanie":"Tanzania",
	u"Ukraine":"Ukraine",
	u"Ouganda":"Uganda",
	u"États-Unis":"United States",
	u"Uruguay":"Uruguay",
	u"Ouzbékistan":"Uzbekistan ",
	u"Vatican":"Holy See (Vatican city)",
	u"Saint-Vincent-et-les-Grenadines":"Saint Vincent and the Grenadines",
	u"Vénézuela":"Venezuela",
	u"Îles Vierges britanniques":"British Virgin Islands",
	u"Îles Vierges des États-Unis":"US Virgin Islands",
	u"Viêt Nam":"Vietnam",
	u"Vanuatu":"Vanuatu",
	u"Wallis-et-Futuna":"Wallis and Futuna",
	u"Samoa":"Samoa",
	u"Yémen":"Yemen",
	u"Mayotte":"Mayotte",
	u"Afrique du Sud":"South Africa",
	u"Zambie":"Zambia",
	u"Zimbabwe":"Zimbabwe",
}