# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_providers', '0002_auto_20170508_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearbitperson',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
