# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_providers', '0003_clearbitperson_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDomainAlias',
            new_name='ClearbitCompanyDomainAlias',
        ),
        migrations.RenameModel(
            old_name='CompanySiteEmailAddress',
            new_name='ClearbitCompanySiteEmailAddress',
        ),
        migrations.RenameModel(
            old_name='CompanySitePhoneNumber',
            new_name='ClearbitCompanySitePhoneNumber',
        ),
        migrations.RenameModel(
            old_name='CompanyTech',
            new_name='ClearbitCompanyTag',
        ),
        migrations.RenameModel(
            old_name='CompanyTag',
            new_name='ClearbitCompanyTech',
        ),
        migrations.RenameModel(
            old_name='PersonGravatarAvatar',
            new_name='ClearbitPersonGravatarAvatar',
        ),
        migrations.RenameModel(
            old_name='PersonGravatarUrl',
            new_name='ClearbitPersonGravatarUrl',
        ),
        migrations.RenameField(
            model_name='clearbitcompanytag',
            old_name='tech',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='clearbitcompanytech',
            old_name='tag',
            new_name='tech',
        ),
    ]
