# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_providers', '0005_auto_20170510_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearbitcompany',
            name='geo_state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitcompany',
            name='geo_street_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitcompany',
            name='geo_sub_premise',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitcompany',
            name='metrics_employees_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitcompany',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitperson',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitperson',
            name='geo_country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitperson',
            name='geo_state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
