# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('euro_price', models.IntegerField()),
                ('monthly_requests', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
